# Jekyll Configuration
theme: jekyll-theme-minimal
title: Yulun Zhuang
description: Robotics PhD at UMich
logo: assets/img/head.png
google_analytics: G-placeholder
url_cv: assets/img/placeholder.jpg
url_github: https://github.com/silvery107
url_email: yulunz@umich.edu
url_linkedin: https://www.linkedin.com/in/yulun107
url_steam: https://steamcommunity.com/id/silvery107
url_scholar: https://scholar.google.com.sg/citations?hl=en&user=z_gDNE0AAAAJ
