# Jekyll Configuration
theme: jekyll-theme-minimal
title: Haoyuan Miao
description: Robotics Engineer at XYZ Robotics Inc.
logo: assets/img/placeholder.png
google_analytics: G-placeholder
url_cv: assets/img/placeholder.jpg
url_github: https://github.com/mhysjtu
url_email: mhysjtu@163.com
url_linkedin: assets/img/placeholder.jpg
